# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Skip these files
exclude: "^\
  (\
  devices/.*/(\
  (.*apollo3\\.h)|\
  (.*MKL02Z4\\.h)|\
  (.*nrf52840\\.h)|\
  (.*samd11.*\\.h)|\
  (.*stm32f4.*xx\\.h))\
  )|\
  (third-party/STM32F40x\\.svd)\
  "

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-executables-have-shebangs # Ensures that (non-binary) executables have a shebang.
      - id: check-json # This hook checks json files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: trailing-whitespace # This hook trims trailing whitespace.

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.5.1
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: [--write]
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      # keep this before clang-tidy, it generates compile_commands.json for it
      - id: compiledb
        name: compiledb
        entry: compiledb
        language: system
        # TODO get this working with ENABLE_MEMFAULT=1, ENABLE_MEMFAULT_DEMO=1,
        args:
          [--overwrite, make, CC=clang, ENABLE_STDIO=1, ENABLE_RTT=1, -n, -B]
        always_run: true
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.4
    hooks:
      - id: clang-format
        args: [--style=file, -i]
        files: src/.*\.c

      - id: clang-tidy
        args: [-checks=clang-diagnostic-return-type]

        # TODO once "ENABLE_MEMFAULT=1, ENABLE_MEMFAULT_DEMO=1" fixed, add src back
        files: src/(interrupts)|(main)\.c
        # files: src/.*\.c

  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        args:
          [
            --enable=all,
            --suppress=unusedFunction,
            --suppress=unmatchedSuppression,
            --suppress=missingIncludeSystem,
            --suppress=toomanyconfigs,
            --error-exitcode=1,
          ]
        files: \.(c|h|cpp)$
