#pragma once

//! @file
//!
//! Copyright (c) Memfault, Inc.
//! See License.txt for details
//!
//! Platform overrides for the default configuration settings in the
//! memfault-firmware-sdk. Default configuration settings can be found in
//! "memfault/config.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MEMFAULT_USE_GNU_BUILD_ID 1

#define MEMFAULT_ASSERT_HALT_IF_DEBUGGING_ENABLED 1

#define MEMFAULT_EVENT_INCLUDE_DEVICE_SERIAL 1

// #define MEMFAULT_PLATFORM_COREDUMP_STORAGE_REGIONS_CUSTOM 1
#if !defined(MEMFAULT_PLATFORM_COREDUMP_STORAGE_RAM_SIZE)
#define MEMFAULT_PLATFORM_COREDUMP_STORAGE_RAM_SIZE 8000
#endif

#if ENABLE_MEMFAULT_HEAP_TRACKING
#define MEMFAULT_COREDUMP_COLLECT_HEAP_STATS 1
#endif

// #define MEMFAULT_COREDUMP_COLLECT_LOG_REGIONS 1

#define MEMFAULT_SDK_LOG_SAVE_DISABLE 1
#define MEMFAULT_DATA_SOURCE_RLE_ENABLED 0
#define MEMFAULT_LOG_DATA_SOURCE_ENABLED 0
#define MEMFAULT_EVENT_STORAGE_READ_BATCHING_ENABLED 0
#define MEMFAULT_TRACE_EVENT_WITH_LOG_FROM_ISR_ENABLED 0
#define MEMFAULT_EVENT_STORAGE_NV_SUPPORT_ENABLED 0
#define MEMFAULT_COLLECT_INTERRUPT_STATE 0
#define MEMFAULT_COLLECT_FAULT_REGS 0
#define MEMFAULT_CRC16_LOOKUP_TABLE_ENABLE 0


// #define MEMFAULT_COMPACT_LOG_ENABLE 1

#ifdef __cplusplus
}
#endif
