name: main-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # checkout v2, with recursive submodule update
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # build the Docker image we use to run the tests
      - name: ci.sh
        run: ./ci.sh
